const cooling_machines = [
    {
      name: 'Refrigerated Containers',
      price: '₹*N/A*',
      coverImage: 'Refrigerated_Container_Cover.png',
      contact: '999999999999',
      detailImage: 'Refrigerated_Container_Detail.png',
      id: 0,
    },
    {
        name: 'FOW (Freeze on Wheels)',
        price: '₹*N/A*',
        coverImage: 'Freeze_on_wheels_cover.png',
        contact: '999999999999',
        detailImage: 'Freeze_on_wheels_detail.png',
        id : 1,
    },
    {
        name: 'Cold Room/ Blast Room/ Small Room',
        price: '₹*N/A*',
        coverImage: 'Cold_Room_Cover.png',
        contact: '999999999999',
        detailImage: 'Cold_Room_Detail.png',
        id : 2,
    },
    {
        name: 'Bulk Milk Chiller/ Cooler',
        price: '₹*N/A*',
        coverImage: 'Bulk_Milk_Chiller_Cover.png',
        contact: '999999999999',
        detailImage: 'Bulk_Milk_Chiller_Detail.png',
        id : 3,
    },
    {
        name: 'Ice Candy Plant',
        price: '₹*N/A*',
        coverImage: 'Ice_Candy_Cover.png',
        contact: '999999999999',
        detailImage: 'Ice_Candy_Detail.png',
        id : 4,
    },
    {
        name: 'Deep & Vertical Freezer',
        price: '₹*N/A*',
        coverImage: 'Vertical_Deep_Freezer_Cover.png',
        contact: '999999999999',
        detailImage: 'Vertical_Deep_Freezer_Detail.png',
        id : 5,
    },
    {
        name: 'Air Cooled & Water Cooled Screw Chiller',
        price: '₹*N/A*',
        coverImage: 'Air_Cool_Screw_Chiller_Cover.png',
        contact: '999999999999',
        detailImage: 'Air_Cool_Screw_Chiller_Detail.png',
        id : 6,
    },
    {
        name: 'Air Cooled & Water Cooled B-PHE Scroll Chiller',
        price: '₹*N/A*',
        coverImage: 'Air_Cool_Scroll_Chiller_Cover.png',
        contact: '999999999999',
        detailImage: 'Air_Cool_Scroll_Chiller_Detail.png',
        id : 7,
    },
    {
        name: 'Cooling Towers',
        price: '₹*N/A*',
        coverImage: 'Cooling_Tower_Cover.png',
        contact: '999999999999',
        detailImage: 'Cooling_Tower_detail.png',
        id : 8,
    },
    // Add more products as needed
  ];

  export default cooling_machines;