const oil_machines = [
    {
      name: 'Multi Sees Oil Extraction Machine Type-1',
      price: '₹15,000',
      coverImage: 'Multi_Type1_Cover.png',
      contact: '999999999999',
      detailImage: 'Multi_Type1_Detail.png',
      id: 0,
    },
    {
        name: 'Multi Sees Oil Extraction Machine Type-2',
        price: '₹25,000',
        coverImage: 'Multi_Type2_Cover.png',
        contact: '999999999999',
        detailImage: 'Multi_Type2_Detail.png',
        id : 1,
    },
    {
        name: 'Multi Sees Oil Extraction Machine Type-3',
        price: '₹65,000',
        coverImage: 'Multi_Type3_Cover.png',
        contact: '999999999999',
        detailImage: 'Multi_Type3_Detail.png',
        id : 2,
    },
    {
        name: 'Multi Sees Oil Extraction Machine Type-4',
        price: '₹80,000',
        coverImage: 'Multi_Type4_Cover.png',
        contact: '999999999999',
        detailImage: 'Multi_Type4_Detail.png',
        id : 3,
    },
    {
        name: 'Multi Sees Oil Extraction Machine Type-5',
        price: '₹1,50,000',
        coverImage: 'Multi_Type5_Cover.png',
        contact: '999999999999',
        detailImage: 'Multi_Type5_Detail.png',
        id : 4,
    },
    {
        name: 'Commercial Hot & Cold Screw Press Machine Type 1',
        price: '₹3,51,640',
        coverImage: 'Commercial_Hot_Cold_Screw_Type1_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Hot_Cold_Screw_Type1_Detail.png',
        id : 5,
    },
    {
        name: 'Commercial Cold Screw Press Machine Type 1',
        price: '₹3,51,640',
        coverImage: 'Commercial_Cold_Screw_Type1_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Hot_Cold_Screw_Type1_Detail.png',
        id : 6,
    },
    {
        name: 'Commercial Hot & Cold Screw Press Machine Type 2',
        price: '₹6,25,400',
        coverImage: 'Commercial_Hot_Cold_Screw_Type2_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Hot_Cold_Screw_Type2_Detail.png',
        id : 7,
    },
    {
        name: 'Commercial Cold Screw Press Machine Type 2',
        price: '₹6,25,400',
        coverImage: 'Commercial_Cold_Screw_Type2_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Cold_Screw_Type2_Detail.png',
        id : 8,
    },
    {
        name: 'Commercial Hot & Cold Screw Press Machine Type 3',
        price: '₹9,09,780',
        coverImage: 'Commercial_Hot_Cold_Screw_Type3_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Hot_Cold_Screw_Type3_Detail.png',
        id : 9,
    },
    {
        name: 'Commercial Cold Screw Press Machine Type 3',
        price: '₹9,09,780',
        coverImage: 'Commercial_Cold_Screw_Type3_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Cold_Screw_Type3_Detail.png',
        id : 10,
    },
    {
        name: 'Commercial Hot & Cold Screw Press Machine Type 4',
        price: '₹17,70,000',
        coverImage: 'Commercial_Hot_Cold_Screw_Type4_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Hot_Cold_Screw_Type4_Detail.png',
        id : 11,
    },
    {
        name: 'Commercial Cold Screw Press Machine Type 4',
        price: '₹17,70,000',
        coverImage: 'Commercial_Cold_Screw_Type4_Cover.png',
        contact: '999999999999',
        detailImage: 'Commercial_Cold_Screw_Type4_Detail.png',
        id : 12,
    },
    // Add more products as needed
  ];

  export default oil_machines;